### ISSUE TITLE
suggest change line 531 and 711 of TextBox.bas 

### ISSUE THREAD

**Issue by chunmingwang** [XusinboyBekchanov/MyFbFramework#10]
**Line 531:**
from
`FText = WInput(LOF(1), #Fn)`
change to
`FText = WInput(LOF(Fn), #Fn)`

**Line 711:** 
from
`iSelEndCol = iSelStart - SendMessage(FHandle, EM_LINEINDEX, iSelEndRow, 0)`
change to
`iSelEndCol = iSelEnd - SendMessage(FHandle, EM_LINEINDEX, iSelEndRow, 0)`

**Comment by XusinboyBekchanov** [comment]
Fixed: TextBox LoadFromFile and GetSel method:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/2bfe752a726b00fda76d47c2ca78be17cc06a483

Thanks for the suggestion.
