### ISSUE TITLE
suggest change line 237 of ComboBoxEdit.bas

### ISSUE THREAD

**Issue by chunmingwang** [XusinboyBekchanov/MyFbFramework#11]
**line 237** 

from
`If FHandle Then Perform(CB_SELECTSTRING, -1, CInt(FText.vptr))`
change to
`If FHandle Then Perform(WM_SETTEXT, -1, CInt(FText.vptr))`

**Comment by XusinboyBekchanov** [comment]
Fixed: ComboBoxEdit Text property:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/5310aab86042ed6897ab16b50616148af77dd952

Thanks for the suggestion.
