### ISSUE TITLE
OnChange event is not workble for ComboBoxEdit

### ISSUE THREAD

**Issue by chunmingwang** [XusinboyBekchanov/MyFbFramework#14]
have to add code for line 456

`				Case CBN_SELCHANGE
					If OnChange Then OnChange(This)
`

**Comment by XusinboyBekchanov** [comment]
For a long time this is the same:
https://github.com/XusinboyBekchanov/MyFbFramework/blob/master/mff/ComboBoxEdit.bas#L457

**Comment by chunmingwang** [comment]
> For a long time this is the same: https://github.com/XusinboyBekchanov/MyFbFramework/blob/master/mff/ComboBoxEdit.bas#L457
Sorry for the wrong line number,

‘If OnChange Then OnChange(This)’

should bellow to 

'Case CBN_EDITCHANGE'

**Comment by XusinboyBekchanov** [comment]
Fixed: OnChange event on ComboBoxEdit:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/f26010b40676728e07e65b0ba3d20349da0e718e

**Comment by chunmingwang** [comment]
fixed.
