### ISSUE TITLE
Suggest adding properties to control the display/hiding of Form Caption

### ISSUE THREAD

**Issue by chunmingwang** [XusinboyBekchanov/MyFbFramework#142]
Suggest adding properties to control the display/hiding of Form Caption

Code example for Windows

```
Dim style As Long = GetWindowLong(Handle, GWL_STYLE)
If ShowCaption Then
	style = style Or WS_CAPTION
Else
	style = style Xor WS_CAPTION
End If
SetWindowLong(Handle, GWL_STYLE, style)
SetWindowPos(Handle, NULL, 0, 0, 0, 0, SWP_NOSIZE Or SWP_NOMOVE Or SWP_NOZORDER Or SWP_FRAMECHANGED)
```

**Comment by XusinboyBekchanov** [comment]
Then we can add this property to the Form.

**Comment by XusinboyBekchanov** [comment]
If you want, you can also send a Pull Request yourself.

**Comment by XusinboyBekchanov** [comment]
I think it's not finished yet.

**Comment by chunmingwang** [comment]
i will try to add property HideCaption for Form

**Comment by chunmingwang** [comment]
I issue a PR to add property HideCaption for Form
https://github.com/XusinboyBekchanov/MyFbFramework/pull/143

**Comment by chunmingwang** [comment]
Thanks!
