### ISSUE TITLE
AddItem is not work correctly of CheckedListBox

### ISSUE THREAD

**Issue by chunmingwang** [XusinboyBekchanov/MyFbFramework#17]
I found AddItem is not work correctly of CheckedListBox

**Comment by XusinboyBekchanov** [comment]
Fixed: CheckedListBox AddItem method:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/efd0938bfb7b9a6e0561fa1ae88f6262b9baac78

Thank you for message.

**Comment by chunmingwang** [comment]
Fixed
