### ISSUE TITLE
MDI main form scrollbar Lightmode still show Darkmode style

### ISSUE THREAD

**Issue by chunmingwang** [XusinboyBekchanov/MyFbFramework#172]
MDI main form scrollbar Lightmode still show Darkmode style

See as screen short following

![image](https://github.com/XusinboyBekchanov/MyFbFramework/assets/35757455/8668951f-e5bc-4d7e-9280-bb833d581b99)

**Comment by XusinboyBekchanov** [comment]
After what steps does this work?
I tried it, I have no problems.

**Comment by chunmingwang** [comment]
After switching between Darkmode and Lightmod using the Darkmode menu
MDI main form scrollbar aways shows in Darkmode style

**Comment by chunmingwang** [comment]
![mdidarkmode](https://github.com/XusinboyBekchanov/MyFbFramework/assets/35757455/c4587971-7d17-4d2a-955d-6edf3e8e8b4b)

**Comment by hustbeef** [comment]
This title bar is purple, can we change the black in dark mode to different colors to accommodate users who prefer a variety of colors.

**Comment by XusinboyBekchanov** [comment]
Fixed: MDIForm on Light mode:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/591db907dcc73b3e1ddca4e27b083316dca8b3d2

**Comment by chunmingwang** [comment]
Thanks!

**Comment by XusinboyBekchanov** [comment]
But after switching between titles it is updated. I'll see if there's a way to fix this.
