### ISSUE TITLE
Dark/Light mode issue of ComboBoxEx in cbDropDown style

### ISSUE THREAD

**Issue by chunmingwang** [XusinboyBekchanov/MyFbFramework#175]
Dark/Light mode issue of ComboBoxEx in cbDropDown style

See as screen short of MdeiaPlayer example

Dark mode

![1716254362026](https://github.com/XusinboyBekchanov/MyFbFramework/assets/35757455/4d962483-f86c-4fed-b932-032cc15da004)

Light mode

![image](https://github.com/XusinboyBekchanov/MyFbFramework/assets/35757455/5eedcc81-0359-4559-8fe2-31fdcd9a4544)

**Comment by hustbeef** [comment]
try replace the code "Case WM_PAINT, WM_ERASEBKGND"  to "Case WM_PAINT"  in control.bas

**Comment by chunmingwang** [comment]
> try replace the code "Case WM_PAINT, WM_ERASEBKGND" to "Case WM_PAINT" in control.bas

I try above change, can't slove the issue.

**Comment by XusinboyBekchanov** [comment]
Improved: ComboBoxEx in Dark mode:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/d8ff5e8ffcc7fd98d1bfba3cdcbc213b89a31c79

**Comment by chunmingwang** [comment]
Thanks for super fast team response.
