### ISSUE TITLE
Caption display abnormality in GroupBox dark mode

### ISSUE THREAD

**Issue by chunmingwang** [XusinboyBekchanov/MyFbFramework#184]
In the NTPClient.vfp example

![1721368993259](https://github.com/user-attachments/assets/705ba5f7-b08a-4c71-8221-b80281b91c99)

I found the caption display abnormality in GroupBox dark mode

![1721368944793](https://github.com/user-attachments/assets/7669d872-2e09-4100-be08-a29cb7aafe83)

Please have a look.

**Comment by XusinboyBekchanov** [comment]
Improved: GroupBox on Dark Mode:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/11703b2915ac5c9ac6098ae5e07d5daf7b5020d1

**Comment by chunmingwang** [comment]
![image](https://github.com/user-attachments/assets/c699027b-dc7c-4361-917b-cf0312b0f93a)


> XusinboyBekchanov

Thanks.
