### ISSUE TITLE
Dark/Light mode issue of ComboBoxEx

### ISSUE THREAD

**Issue by chunmingwang** [XusinboyBekchanov/MyFbFramework#190]
The problem reproduction method is as follows:

1. Run FileBrowser in Examples.
2. Click the minimize button of the FileBrowser window to minimize the window.
3. Click FileBrowser in the taskbar to restore the window.
4. It can be seen that the ComboBoxEx control in the address bar of the following FileBrowser is displayed abnormally.

![1725589903697](https://github.com/user-attachments/assets/6f2a0dff-d136-4deb-9341-28d89546e63e)

Please take a look at this issue.

**Comment by XusinboyBekchanov** [comment]
Does this fix it?
https://github.com/XusinboyBekchanov/MyFbFramework/commit/a48cef2130e9c4594b90712f18ce7cfc1d7513a7

**Comment by chunmingwang** [comment]
I have tested it, the issue above has been resolved.
Thanks.
