### ISSUE TITLE
ContextMenu issue on the ListView control

### ISSUE THREAD

**Issue by chunmingwang** [XusinboyBekchanov/MyFbFramework#191]
The problem reproduction method is as follows:

1. Run FileBrowser in Examples.
2. Activate the ContextMenu on the ListView control with the mouse right button click.
3. Move mouse cursor and select the "Max" menu with the mouse left button click.
4. At this time, when moving the mouse cursor in ListView, ListView is in an abnormal selection state.

![image](https://github.com/user-attachments/assets/15af9f68-3b89-4f0e-9150-26c8b6fe2641)

Please take a look at what causes this.

**Comment by XusinboyBekchanov** [comment]
Fixed:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/3931748f550b4a7a68c2077483abda8e283434b7

**Comment by chunmingwang** [comment]
Thanks.
