### ISSUE TITLE
How to use the mouse click event in the StatusBar control.

### ISSUE THREAD

**Issue by chunmingwang** [XusinboyBekchanov/MyFbFramework#192]
I don't know how to obtain which StatusPanel the mouse button click on the StatusBar belongs to.
Can it be like the ToolBar control, It has an OnButtonClick event that can tell which Button is click. Also generate an OnPanelClick event for StatusBar control that returns which StatusPanel is clicked by the mouse.

Please help. Thank you.

**Comment by XusinboyBekchanov** [comment]
Added: OnPanelClick And OnPanelDblClick events to StatusBar, Added: StatusBar Example:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/e06c5930aaf49ddc95ad6388edac7c07058e6943

**Comment by chunmingwang** [comment]
Thanks!
