### ISSUE TITLE
I have recently discovered some issues in my computer environment

### ISSUE THREAD

**Issue by chunmingwang** [XusinboyBekchanov/MyFbFramework#198]
My OS and Environment

1. OS: Windows 10, 64.
2. Download Github vfbe & mff.
3. Using FBC version: FreeBASIC Compiler - Version 1.20.0 (2024-06-17).
4. Compile mff64 parameters: "fbc64. exe" - b "mff. bi" "mff. rc" - x "../mff64. dll" - dll-v - exx
5. Compile VFBE64 parameters: "fbc64. exe" "VisualFBEditor. bas" "VisualFBEditor. rc" - i "../Controls/MyFbFramework" - x "../VisualFBEditor64. exe" - s gui - v - exx

Issues found:

1. In VFBE64 ctrl+shift+n new project ->GUI application, double clicking on the OnCreate event in the events list of Form1, then vfbe64 crash.
3. VFBE64 is becoming increasingly prone to crashes, and sometimes closing VFBE64 and exiting can also cause crashes.
4. Example gidpClock/gidpGoldFish/MidiKeyboard/MidiPlayer/MultipleDisplay/FileBrowser/ChineseCalendar/DynamicControl Compile with GUI/64, if run examples and click close button, exiting with crash.

Please help to check.

**Comment by hustbeef** [comment]
It's unusual to receive a return error message after closing the form in the MultipleDisplay.vfp project.

**Comment by XusinboyBekchanov** [comment]
Will it be fixed after this?
https://github.com/XusinboyBekchanov/MyFbFramework/commit/b889a0a72e1abe537040c358a6b8f73144a67f3b

**Comment by chunmingwang** [comment]
Yes it's fixed, Thanks!

**Comment by hustbeef** [comment]
OH, My gods.  Yes it's fixed, Thanks!  But it's unusual to receive a return error message after closing the form in the Examples MultipleDisplay.vfp project.

**Comment by hustbeef** [comment]
I'm going to post the optimization code for MFF .

**Comment by hustbeef** [comment]
I change back the code (line 1140  of TabWindow.bas) . 
                   "If ptabCode->TabCount > 1 Then _Delete(tb)"     to    "_Delete(tb)"
Got the Error message: Handler line 1421.  Handler function: TabWindow.ReadObjProperty

**Comment by hustbeef** [comment]
It is conflict with Code in Sub frmMain_Close. " If Not CloseSession Then Action = 0: Return "
![image](https://github.com/user-attachments/assets/171d0477-1479-4024-ba28-5d2acdb34e36)

**Comment by chunmingwang** [comment]
i reopen this issue, Bustbeef still have some commented.

**Comment by XusinboyBekchanov** [comment]
Maybe you have an error because of this:
https://github.com/XusinboyBekchanov/MyFbFramework/pull/199#issue-2615478360

There is an array of pointers, deleted using the Delete command.

**Comment by hustbeef** [comment]
> Maybe you have an error because of this: [#199 (comment)](https://github.com/XusinboyBekchanov/MyFbFramework/pull/199#issue-2615478360)
> 
> There is an array of pointers, deleted using the Delete command.
1. It is happen 2 years before.  the root reason of slow down I think that the allocating memory is frag in function LoadFunctions. So maybe we can try  Pre-allocating memory.  
2. https://www.freebasic.net/forum/viewtopic.php?p=305108#p305108 , So I changed  _CAllocate to _Allocate.  FXM said that: it is surprising when using 'New', we find an execution time comparable to that of 'Allocate' (better than 'CAllocate'), while the memory is set to 0. Example with an UDT of 3 pointers to be compatible with 'New':

**Comment by hustbeef** [comment]
There is an array of pointers, deleted using the Delete command.
Which code? Please correct the code if you find the error. I only change the following code in this time. 
		- If Tabs <> 0 Then _Deallocate(Tabs)
		- WDeAllocate(FGroupName)
		+ If Tabs <> 0 Then _Delete(Tabs)
		+ If FGroupName Then _Deallocate(FGroupName)
		'UnregisterClass "TabControl", GetModuleHandle(NULL)

**Comment by XusinboyBekchanov** [comment]
>Which code? Please correct the code if you find the error. I only change the following code in this time.
>- If Tabs <> 0 Then _Deallocate(Tabs)
>- WDeAllocate(FGroupName)
>+ If Tabs <> 0 Then _Delete(Tabs)
>+ If FGroupName Then _Deallocate(FGroupName)
>'UnregisterClass "TabControl", GetModuleHandle(NULL)

And I told you about this error in this topic: https://github.com/XusinboyBekchanov/MyFbFramework/pull/199#issue-2615478360, and did not merge your request with the main branch, waiting for you to fix this error.

**Comment by hustbeef** [comment]
I try  to improve MFF.  Now found one more： " If Value <> *FImageKey " Then  change to " If FImageKey = 0 OrElse Value <> *FImageKey Then "

**Comment by XusinboyBekchanov** [comment]
I reverted to the old version on Deallocate:
https://github.com/XusinboyBekchanov/MyFbFramework/pull/199/commits/a49b902434b5be383b298152ee782538a6cf6e9f

**Comment by XusinboyBekchanov** [comment]
Merged your request after correcting the above error in your request:
https://github.com/XusinboyBekchanov/MyFbFramework/pull/199

**Comment by hustbeef** [comment]
Is Tabs a type pointer? If so, why is Deallocate necessary?   I’m not insisting; I just don’t understand.

**Comment by XusinboyBekchanov** [comment]
>Is Tabs a type pointer? If so, why is Deallocate necessary? I’m not insisting; I just don’t understand.

This is the declaration of this variable:
![image](https://github.com/user-attachments/assets/083c9970-743e-496d-911d-fa24e7a13120)

This is the allocation of space for TabPage Ptr:
![image](https://github.com/user-attachments/assets/ab92f6c6-6a86-414c-80b4-975d3193d7d7)

That is, TabPage Ptr Ptr is an array of TabPage Pointers (TabPage Ptrs):

Tabs[0] is the first TabPage Ptr
Tabs[1] is the second TabPage Ptr
Tabs[2] is the third TabPage Ptr
... and so on

They can be freed as _Delete(Tabs[0]), _Delete(Tabs[1]), _Delete(Tabs[2]), ... for each element, but they cannot be freed as _Delete(Tabs). Because this array can only be created as Tabs = Allocate(...) or Tabs = Reallocate(...) and freed as Deallocate(Tabs).

**Comment by hustbeef** [comment]
Thanks.  Now I understands.

**Comment by chunmingwang** [comment]
It has reached a consensus
