### ISSUE TITLE
Please add TAB and SHIFT+TAB support

### ISSUE THREAD

**Issue by JanuszChmiel** [XusinboyBekchanov/MyFbFramework#2]
I know, that making attractive GUI toolkit for sighted is not easy. And making The GUI which have been created with it fully accessible is very complex. But if I can valuably and kindly please you. Would you add focus support with keyboard on The objects where is it possible? Or is it only necessary to type some line of code so every object can get focus so arrow keys and TAB can be used to switch between various GUI elements? I know, that all objects can not be focusable. Such as canvas or brush. But The following objects could have a possibility to get focus automatically at app startup. ComboBoxEdit
ComboBoxEx
CommandButton
GroupBox
CheckBox
CheckedListBox
List
ListItems
ListView
MonthCalendar
RadioButton
RichTextBox
TrackBar
TreeListView
TreeView

**Comment by XusinboyBekchanov** [comment]
Yes, I will fix tabs.

**Comment by XusinboyBekchanov** [comment]
Added in new version 1.2.3

**Comment by JanuszChmiel** [comment]
Very well done. Thank you very much for new fetures and especially for
adding TAB or SHIFT+TAB support. So it should not be necessary to give
object The focus? I will test The Gui behaviour and really thank you very
much again.
Now I can concentrate for learning Free Basic and to understand all of yours
framework functions and subs.

**Comment by JanuszChmiel** [comment]
aVery well done. But please be careful, because
frm.Center
do not work. Compiler show error.
But object really get focus correctly. I will test it on listwiev and
treewiev, because it is being used also on yours Visual IDE settings GUI.

**Comment by XusinboyBekchanov** [comment]
In the new version has CenterToScreen and CenterToParent as in VB.NET
