### ISSUE TITLE
where is mff/SearchBox.bi ?

### ISSUE THREAD

**Issue by tomasmetal23** [XusinboyBekchanov/MyFbFramework#202]
![image](https://github.com/user-attachments/assets/738513f0-ea06-44e3-9e36-0cf0f0fccd1c)

**Comment by XusinboyBekchanov** [comment]
Here too:
https://github.com/XusinboyBekchanov/MyFbFramework/blob/master/mff/SearchBox.bi

**Comment by XusinboyBekchanov** [comment]
You need also install gtk3:
`sudo apt-get install libgtk-3-dev`

**Comment by tomasmetal23** [comment]
Thank you! I had downloaded it from the releases section, and for some reason, that file wasn’t there. But I did a 'git clone,' and everything worked perfectly

**Comment by XusinboyBekchanov** [comment]
>Thank you! I had downloaded it from the releases section, and for some reason, that file wasn’t there. But I did a 'git clone,' and everything worked perfectly

The SearchBox component was not in version 1.3.5, it appeared in the not yet released version 1.3.6.
