### ISSUE TITLE
Timer component Interval value "0" is not a valid value

### ISSUE THREAD

**Issue by stan1958** [XusinboyBekchanov/MyFbFramework#204]
Timer component Interval value "0" is not a valid value, virtually it behaves as infinite value.
Is it intentional? 

Can test the this behavior in cairo_GDI example.

Thanks

**Comment by XusinboyBekchanov** [comment]
TimerComponent runs when Interval is greater than zero.

**Comment by stan1958** [comment]
thanks for the clarification
