### ISSUE TITLE
property Position issue of ScrollBar in Windows

### ISSUE THREAD

**Issue by chunmingwang** [XusinboyBekchanov/MyFbFramework#23]
I found the value of position cannot be saved at form desing mode and is always reset.

**Comment by XusinboyBekchanov** [comment]
Fixed: Saving ScrollBar Position on Design mode:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/e607d88bd1573e22f5cdfc2c2eff6714f9fd9381
