### ISSUE TITLE
When click the mouse once, the control in the GropBox will generate OnClick event twice at Windows

### ISSUE THREAD

**Issue by chunmingwang** [XusinboyBekchanov/MyFbFramework#24]
When click the mouse once, the control in the GropBox will generate OnClick event twice at Windows

**Comment by XusinboyBekchanov** [comment]
Fixed: Twice OnClick event on the controls in GroupBox:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/4a55e711d7fe5c8511dbfbeb54a5e0a6af8236fa
