### ISSUE TITLE
Cannot edit Sytle properties on Comboboxedit in design mode

### ISSUE THREAD

**Issue by chunmingwang** [XusinboyBekchanov/MyFbFramework#26]
![Untitled](https://user-images.githubusercontent.com/35757455/153321017-d6042d1f-8135-4e1b-8497-6ee1f65d2527.png)
Cannot edit Sytle properties on Comboboxedit in design mode
no exist Sytle properties on Comboboxedit in design mode

**Comment by XusinboyBekchanov** [comment]
Fixed: Showing Virtual Properties in Property Grid:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/a050495e9e5d3d9b76dd2396909ce8994e840d1a

**Comment by chunmingwang** [comment]
![Untitled](https://user-images.githubusercontent.com/35757455/153333177-7a5473d9-20ca-4dc5-bf26-45a390a26eb7.png)
Fixed.
