### ISSUE TITLE
Got a type mismatch error even compile for console was activated.

### ISSUE THREAD

**Issue by rexxitall** [XusinboyBekchanov/MyFbFramework#3]
I included the framework to get some helper function - the dictionarys to be exactly.

Seems even if the console subsystem is -s console  the GUI menu items get initialized.
Of course there is no form or gui, it can just fail.

![image](https://user-images.githubusercontent.com/22050310/85433477-cabe4880-b584-11ea-97ac-d031f190b513.png)

its some Kind of new bug. Not happens last week.

i use windows, so i guess the line
	#ifndef __USE_GTK__...

is not enough to avoid this error.

Property MenuItem.Image(value As My.Sys.Drawing.BitmapType)
	FImage = value
	#ifndef __USE_GTK__
		Dim mii As MENUITEMINFOW
		mii.cbSize = SizeOf(mii)
		mii.fMask = MIIM_BITMAP
		mii.hbmpItem = value.Handle
		
		SetItemInfo mii

	#endif
End Property

Property MenuItem.ImageIndex(value As Integer)
	FImageIndex = value
	If value <> -1 AndAlso owner AndAlso owner->imageslist Then
		#ifndef __USE_GTK__
			FImage = owner->imageslist->GetIcon(value).ToBitmap
			
			Dim mii As MENUITEMINFOW
			mii.cbSize = SizeOf(mii)
			mii.fMask = MIIM_BITMAP
			mii.hbmpItem = FImage 'HBMMENU_CALLBACK

			SetItemInfo mii

		#endif
	End If
End Property

**Comment by XusinboyBekchanov** [comment]
How include it?
So?
`#Include "mff/mff.bi"`

**Comment by XusinboyBekchanov** [comment]
Removed Control.bi dependence from ListItems
https://github.com/XusinboyBekchanov/MyFbFramework/commit/e3ccb4e64b3134839b0b74c6b3de089ba23cbb51

Now, when include the Dictionary.bi, WStringList.bi and IniFile.bi will not compile unnecessary files (such as Control.bi, Menus.bi and etc.).

**Comment by rexxitall** [comment]
Great :)
