### ISSUE TITLE
Property Visible doesn't work of MenuItem in Windows

### ISSUE THREAD

**Issue by chunmingwang** [XusinboyBekchanov/MyFbFramework#30]
Property Visible doesn't work of MenuItem in Windows

**Comment by XusinboyBekchanov** [comment]
Fixed: Changing MenuItem Properties from Property Grid:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/b220079f6c8e65756de42ce501cd7ba1ef871f1c

Fixed: MenuItem.Visible property:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/2049718c691769deb04a61885349474dcdbc2213
