### ISSUE TITLE
errors in GridData.bi

### ISSUE THREAD

**Issue by retsyo** [XusinboyBekchanov/MyFbFramework#38]
C:\Users\USER\Downloads\VisualFBEditor.master\MyFbFramework\mff>e:\prg\BASIC\fb\FreeBASIC-1.09.0-win64\fbc -b "mff.bi" "mff.rc" -dll -x "../mff64.dll"
C:\Users\USER\Downloads\VisualFBEditor.master\MyFbFramework\mff\GridData.bi(57) error 4: Duplicated definition, GridSortStyle
C:\Users\USER\Downloads\VisualFBEditor.master\MyFbFramework\mff\GridData.bi(82) error 4: Duplicated definition, GridColumnFormat

C:\Users\USER\Downloads\VisualFBEditor.master\MyFbFramework\mff>e:\prg\BASIC\fb\FreeBASIC-1.09.0-win32\fbc -b "mff.bi" "mff.rc" -dll -x "../mff32.dll"
C:\Users\USER\Downloads\VisualFBEditor.master\MyFbFramework\mff\GridData.bi(57) error 4: Duplicated definition, GridSortStyle
C:\Users\USER\Downloads\VisualFBEditor.master\MyFbFramework\mff\GridData.bi(82) error 4: Duplicated definition, GridColumnFormat

**Comment by XusinboyBekchanov** [comment]
[Fixed: Compiling GridData control](https://github.com/XusinboyBekchanov/MyFbFramework/commit/67807b9f89dcaa2d83fe6cb5c1918a497010625e)

Still have to work with this control to increase the speed.

**Comment by XusinboyBekchanov** [comment]
Compilation error fixed.
