### ISSUE TITLE
Item not defined error

### ISSUE THREAD

**Issue by rexxitall** [XusinboyBekchanov/MyFbFramework#4]
![image](https://user-images.githubusercontent.com/22050310/86003436-0ee09b80-ba12-11ea-9ae1-5d13d9a6e723.png)
Hi, Framework doesnt compiles until i comented Items Parent out.  error 18 Element not defined Parent

**Comment by XusinboyBekchanov** [comment]
Ok, thank you, I commented it:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/6836941ab136bd6de64fe94cfa2f19d6a195dbad
