### ISSUE TITLE
Problem compiling under Raspbian linux (arm)

### ISSUE THREAD

**Issue by SComps** [XusinboyBekchanov/MyFbFramework#48]
While compiling VisualFBEditor, I was unable to compile MyFBFramework resulting in the following output.  Any ideas on how I might correct this.  I'm sure it's something I'm missing.  Thank you in advance.  The code attempting to compile was git clone done immediately before trying to compile it.

pi@raspberrypi:~/VisualFBEditor/MyFbFramework/MyFbFramework/mff $ fbc -v -b "mff.bi" -dll -x "../libmff32_gtk3.so" -d __USE_GTK3__
FreeBASIC Compiler - Version 1.10.0 (2022-04-08), built for linux-arm (32bit)
Copyright (C) 2004-2021 The FreeBASIC development team.
target:       linux-arm, armv7-a, 32bit
backend:      gcc
compiling:    mff.bi -o mff.c (main module)
/home/pi/VisualFBEditor/MyFbFramework/MyFbFramework/mff/Header.bas(664) error 286: Unsupported statement in -gen gcc mode
/home/pi/VisualFBEditor/MyFbFramework/MyFbFramework/mff/Header.bas(669) error 286: Unsupported statement in -gen gcc mode, found 'va_arg'
/home/pi/VisualFBEditor/MyFbFramework/MyFbFramework/mff/Header.bas(706) error 286: Unsupported statement in -gen gcc mode, found 'va_next'

**Comment by SComps** [comment]
I managed to get it to build by commenting out the offending lines above, but I'm pretty sure that's probably not the best way to resolve the problem.  From what I've seen of this framework and VisualFBEditor...  VERY nice work guys!  Thank you!

**Comment by XusinboyBekchanov** [comment]
>While compiling VisualFBEditor, I was unable to compile MyFBFramework resulting in the following output.

Fixed and Improved: AddRange control methods are available in gcc backend and 64-bit:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/9e72f7f7f66e512fd52b57266359c68efaf2d9e9

>From what I've seen of this framework and VisualFBEditor... VERY nice work guys! Thank you!

Thanks for good words.

**Comment by XusinboyBekchanov** [comment]
I think the problem is solved.
