### ISSUE TITLE
Apply DarkMode will changed the font style of CheckBox if it is in GorupBox

### ISSUE THREAD

**Issue by chunmingwang** [XusinboyBekchanov/MyFbFramework#52]
Screenshot see as the attached

Before SetDarkMode
![Untitled0](https://user-images.githubusercontent.com/35757455/163310328-5f1723b9-6d17-40cb-a81f-d8b7a5c1b6d2.png)

After SetDarkMode
![Untitled1](https://user-images.githubusercontent.com/35757455/163310364-4430068c-aac9-4672-ad7a-644aaa9dc173.png)

InitDarkMode

```
	
	Private Sub Form1Type.CheckBox1_Click_(ByRef Sender As CheckBox)
		*Cast(Form1Type Ptr, Sender.Designer).CheckBox1_Click(Sender)
	End Sub
	
	InitDarkMode()
	
	Dim Shared Form1 As Form1Type
	
	#ifndef _NOT_AUTORUN_FORMS_
		#define _NOT_AUTORUN_FORMS_
		
		Form1.Show
		
		App.Run
	#endif
'#End Region

```

SetDarkMode

```
Private Sub Form1Type.CheckBox1_Click(ByRef Sender As CheckBox)
	SetDarkMode(CheckBox1.Checked , CheckBox1.Checked)
End Sub

```

**Comment by XusinboyBekchanov** [comment]
Fixed: CheckBox Font in Dark Mode:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/ae18368639847acf233a4a4aea84e64671aee0ed

**Comment by chunmingwang** [comment]
Tested and it is fixed
