### ISSUE TITLE
sorting bug in GridData

### ISSUE THREAD

**Issue by retsyo** [XusinboyBekchanov/MyFbFramework#54]
when click the percentage column, it sorts in a wrong way. It seems that the value is treated as string
![mathml](https://user-images.githubusercontent.com/7960913/164586915-6b14ced1-25aa-45e9-96c0-0f9d2398bd3f.png)

**Comment by XusinboyBekchanov** [comment]
Fixed: GridData example: sorting by numbers:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/d1a515f0d5d264f452eac144eebd60ac47b30bcf
