### ISSUE TITLE
ComboBoxEx Incomplete display of long text

### ISSUE THREAD

**Issue by chunmingwang** [XusinboyBekchanov/MyFbFramework#75]
Original text as following

```
936 - gb2312 - ANSI/OEM Simplified Chinese (PRC, Singapore); Chinese Simplified (GB2312)
949 - ks_c_5601-1987 - ANSI/OEM Korean (Unified Hangul Code)
950 - big5 - ANSI/OEM Traditional Chinese (Taiwan; Hong Kong SAR, PRC); Chinese Traditional (Big5)
1026 - IBM1026 - IBM EBCDIC Turkish (Latin 5)
1047 - IBM01047 - IBM EBCDIC Latin 1/Open System
1140 - IBM01140 - IBM EBCDIC US-Canada (037 + Euro symbol); IBM EBCDIC (US-Canada-Euro)
1141 - IBM01141 - IBM EBCDIC Germany (20273 + Euro symbol); IBM EBCDIC (Germany-Euro)
1142 - IBM01142 - IBM EBCDIC Denmark-Norway (20277 + Euro symbol); IBM EBCDIC (Denmark-Norway-Euro)
```

Incomplete display in ComboBoxEx as following

![Untitled](https://user-images.githubusercontent.com/35757455/180137701-4a419caa-4dbd-4658-a93b-52695a5900e2.png)

**Comment by XusinboyBekchanov** [comment]
Fixed: Display of ComboBoxEx items with long text:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/c10f34c8ba04c03897d1301c8222dcb2b049e577

Thanks.

**Comment by chunmingwang** [comment]
Thanks.
![Untitled](https://user-images.githubusercontent.com/35757455/180673974-55d21352-fdd7-4ccc-ae76-87f5dbe6609d.png)
