### ISSUE TITLE
ComboBoxEx cannot trigger KeyPress, KeyDown, KeyUp event

### ISSUE THREAD

**Issue by chunmingwang** [XusinboyBekchanov/MyFbFramework#76]
ComboBoxEx cannot trigger KeyPress, KeyDown, KeyUp event

**Comment by XusinboyBekchanov** [comment]
Improved: ComboBoxEx events:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/73d1a2cec633e6aff72d6a0948447406c39852f9

**Comment by chunmingwang** [comment]
Works for cbSimple, cbDropDown style,
but still not work for cbDropDownList, cbOwnerDrawFixed, cbOwnerDrawVariable.
is it normal?

**Comment by XusinboyBekchanov** [comment]
>is it normal?
Now check.

Improved: ComboBoxEx events:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/df741738c571ddd6f8c0eed2c8ff1f01d0921a11

**Comment by chunmingwang** [comment]
Thanks!
