### ISSUE TITLE
Text editor cannot input text with length greater than width in ComboBoxEx at style cbDropDown

### ISSUE THREAD

**Issue by chunmingwang** [XusinboyBekchanov/MyFbFramework#77]
Text editor cannot input text with length greater than width in ComboBoxEx at style cbDropDown

**Comment by chunmingwang** [comment]
also can't input text with length greater than width at style cbSimple

**Comment by XusinboyBekchanov** [comment]
Fixed: ComboBoxEx Text Limit:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/9b6cfd88863160e8f6c2afe99e4aec0cd4b78123

**Comment by chunmingwang** [comment]
Thanks!
