### ISSUE TITLE
Menu Enabled status changed not redraw to new status

### ISSUE THREAD

**Issue by chunmingwang** [XusinboyBekchanov/MyFbFramework#81]
Menu Enabled status changed not redraw to new status

**Comment by XusinboyBekchanov** [comment]
Improved: Disabled menu items and tool buttons will be colored correctly in design mode:
https://github.com/XusinboyBekchanov/VisualFBEditor/commit/758545f0335bda0f894e4944b658eec31e4257a6

**Comment by chunmingwang** [comment]
Thanks, not only in design time, also in run time

**Comment by XusinboyBekchanov** [comment]
It works:
![image](https://user-images.githubusercontent.com/32607344/187599836-525a4e0d-3a42-4d13-bd47-126a705ff223.png)

**Comment by XusinboyBekchanov** [comment]
It turns out that the Top menu is not drawn.

**Comment by XusinboyBekchanov** [comment]
Fixed: Drawing of the top menu when enabling and disabling elements of the top menu:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/fb370819649956bf4734326fddbe6aeb40b3bb80

**Comment by chunmingwang** [comment]
Thanks!
